testC<-function(){ parseChord('C', c('C','E','G')) }
testCs<-function(){ parseChord('Cs', c('Cs','F','Gs')) }
testCs<-function(){ parseChord('Cs', c('Cs','F','Gs')) }
testD<-function(){ parseChord('D', c('D','Fs','A')) }
testDs<-function(){ parseChord('Ds', c('Ds','G','As')) }
testDs<-function(){ parseChord('Ds', c('Ds','G','As')) }
testE<-function(){ parseChord('E', c('E','Gs','B')) }
testF<-function(){ parseChord('F', c('F','A','C')) }
testFs<-function(){ parseChord('Fs', c('Fs','As','Cs')) }
testFs<-function(){ parseChord('Fs', c('Fs','As','Cs')) }
testG<-function(){ parseChord('G', c('G','B','D')) }
testGs<-function(){ parseChord('Gs', c('Gs','C','Ds')) }
testGs<-function(){ parseChord('Gs', c('Gs','C','Ds')) }
testA<-function(){ parseChord('A', c('A','Cs','E')) }
testAs<-function(){ parseChord('As', c('As','D','F')) }
testAs<-function(){ parseChord('As', c('As','D','F')) }
testB<-function(){ parseChord('B', c('B','Ds','Fs')) }
testCm<-function(){ parseChord('Cm', c('C','Ds','G')) }
testCsm<-function(){ parseChord('Csm', c('Cs','E','Gs')) }
testCsm<-function(){ parseChord('Csm', c('Cs','E','Gs')) }
testDm<-function(){ parseChord('Dm', c('D','F','A')) }
testDsm<-function(){ parseChord('Dsm', c('Ds','Fs','As')) }
testDsm<-function(){ parseChord('Dsm', c('Ds','Fs','As')) }
testEm<-function(){ parseChord('Em', c('E','G','B')) }
testFm<-function(){ parseChord('Fm', c('F','Gs','C')) }
testFsm<-function(){ parseChord('Fsm', c('Fs','A','Cs')) }
testFsm<-function(){ parseChord('Fsm', c('Fs','A','Cs')) }
testGm<-function(){ parseChord('Gm', c('G','As','D')) }
testGsm<-function(){ parseChord('Gsm', c('Gs','B','Ds')) }
testGsm<-function(){ parseChord('Gsm', c('Gs','B','Ds')) }
testAm<-function(){ parseChord('Am', c('A','C','E')) }
testAsm<-function(){ parseChord('Asm', c('As','Cs','F')) }
testAsm<-function(){ parseChord('Asm', c('As','Cs','F')) }
testBm<-function(){ parseChord('Bm', c('B','D','Fs')) }
testCaug<-function(){ parseChord('Caug', c('C','E','Gs')) }
testCsaug<-function(){ parseChord('Csaug', c('Cs','F','A')) }
testCsaug<-function(){ parseChord('Csaug', c('Cs','F','A')) }
testDaug<-function(){ parseChord('Daug', c('D','Fs','As')) }
testDsaug<-function(){ parseChord('Dsaug', c('Ds','G','B')) }
testDsaug<-function(){ parseChord('Dsaug', c('Ds','G','B')) }
testEaug<-function(){ parseChord('Eaug', c('E','Gs','C')) }
testFaug<-function(){ parseChord('Faug', c('F','A','Cs')) }
testFsaug<-function(){ parseChord('Fsaug', c('Fs','As','D')) }
testFsaug<-function(){ parseChord('Fsaug', c('Fs','As','D')) }
testGaug<-function(){ parseChord('Gaug', c('G','B','Ds')) }
testGsaug<-function(){ parseChord('Gsaug', c('Gs','C','E')) }
testGsaug<-function(){ parseChord('Gsaug', c('Gs','C','E')) }
testAaug<-function(){ parseChord('Aaug', c('A','Cs','F')) }
testAsaug<-function(){ parseChord('Asaug', c('As','D','E')) }
testAsaug<-function(){ parseChord('Asaug', c('As','D','Fs')) }
testBaug<-function(){ parseChord('Baug', c('B','Ds','G')) }
testCdim<-function(){ parseChord('Cdim', c('C','Ds','Fs')) }
testCsdim<-function(){ parseChord('Csdim', c('Cs','E','G')) }
testCsdim<-function(){ parseChord('Csdim', c('Cs','E','G')) }
testDdim<-function(){ parseChord('Ddim', c('D','F','Gs')) }
testDsdim<-function(){ parseChord('Dsdim', c('Ds','Fs','A')) }
testDsdim<-function(){ parseChord('Dsdim', c('Ds','Fs','A')) }
testEdim<-function(){ parseChord('Edim', c('E','G','As')) }
testFdim<-function(){ parseChord('Fdim', c('F','Gs','B')) }
testFsdim<-function(){ parseChord('Fsdim', c('Fs','A','C')) }
testFsdim<-function(){ parseChord('Fsdim', c('Fs','A','C')) }
testGdim<-function(){ parseChord('Gdim', c('G','As','Cs')) }
testGsdim<-function(){ parseChord('Gsdim', c('Gs','B','D')) }
testGsdim<-function(){ parseChord('Gsdim', c('Gs','B','D')) }
testAdim<-function(){ parseChord('Adim', c('A','C','Ds')) }
testAsdim<-function(){ parseChord('Asdim', c('As','Cs','E')) }
testAsdim<-function(){ parseChord('Asdim', c('As','Cs','Fb (E)')) }
testBdim<-function(){ parseChord('Bdim', c('B','D','F')) }
testC7<-function(){ parseChord('C7', c('C','E','G','As')) }
testCs7<-function(){ parseChord('Cs7', c('Cs','F','Gs','B')) }
testCs7<-function(){ parseChord('Cs7', c('Cs','F','Gs','B')) }
testD7<-function(){ parseChord('D7', c('D','Fs','A','C')) }
testDs7<-function(){ parseChord('Ds7', c('Ds','G','As','Cs')) }
testDs7<-function(){ parseChord('Ds7', c('Ds','G','As','Cs')) }
testE7<-function(){ parseChord('E7', c('E','Gs','B','D')) }
testF7<-function(){ parseChord('F7', c('F','A','C','Ds')) }
testFs7<-function(){ parseChord('Fs7', c('Fs','As','Cs','E')) }
testFs7<-function(){ parseChord('Fs7', c('Fs','As','Cs','E')) }
testG7<-function(){ parseChord('G7', c('G','B','D','F')) }
testGs7<-function(){ parseChord('Gs7', c('Gs','C','Ds','Fs')) }
testGs7<-function(){ parseChord('Gs7', c('Gs','C','Ds','Fs')) }
testA7<-function(){ parseChord('A7', c('A','Cs','E','G')) }
testAs7<-function(){ parseChord('As7', c('As','D','F','Gs')) }
testAs7<-function(){ parseChord('As7', c('As','D','F','Gs')) }
testB7<-function(){ parseChord('B7', c('B','Ds','Fs','A')) }
testC7b5<-function(){ parseChord('C7(b5)', c('C','E','Fs','As')) }
testCs7b5<-function(){ parseChord('Cs7(b5)', c('Cs','F','G','B')) }
testCs7b5<-function(){ parseChord('Cs7(b5)', c('Cs','F','G','B')) }
testD7b5<-function(){ parseChord('D7(b5)', c('D','Fs','Gs','C')) }
testDs7b5<-function(){ parseChord('Ds7(b5)', c('Ds','G','A','Cs')) }
testDs7b5<-function(){ parseChord('Ds7(b5)', c('Ds','G','A','Cs')) }
testE7b5<-function(){ parseChord('E7(b5)', c('E','Gs','As','D')) }
testF7b5<-function(){ parseChord('F7(b5)', c('F','A','B','Ds')) }
testFs7b5<-function(){ parseChord('Fs7(b5)', c('Fs','As','C','E')) }
testFs7b5<-function(){ parseChord('Fs7(b5)', c('Fs','As','C','E')) }
testG7b5<-function(){ parseChord('G7(b5)', c('G','B','Cs','F')) }
testGs7b5<-function(){ parseChord('Gs7(b5)', c('Gs','C','D','Fs')) }
testGs7b5<-function(){ parseChord('Gs7(b5)', c('Gs','C','D','Fs')) }
testA7b5<-function(){ parseChord('A7(b5)', c('A','Cs','Ds','G')) }
testAs7b5<-function(){ parseChord('As7(b5)', c('As','D','E','Gs')) }
testAs7b5<-function(){ parseChord('As7(b5)', c('As','D','E','Gs')) }
testB7b5<-function(){ parseChord('B7(b5)', c('B','Ds','F','A')) }
testCdim7<-function(){ parseChord('Cdim7', c('C','Ds','Fs','A')) }
testCsdim7<-function(){ parseChord('Csdim7', c('Cs','E','G','As')) }
testCsdim7<-function(){ parseChord('Csdim7', c('Cs','E','G','As')) }
testDdim7<-function(){ parseChord('Ddim7', c('D','F','Gs','B')) }
testDsdim7<-function(){ parseChord('Dsdim7', c('Ds','Fs','A','C')) }
testDsdim7<-function(){ parseChord('Dsdim7', c('Ds','Fs','A','C')) }
testEdim7<-function(){ parseChord('Edim7', c('E','G','As','Cs')) }
testFdim7<-function(){ parseChord('Fdim7', c('F','Gs','B','D')) }
testFsdim7<-function(){ parseChord('Fsdim7', c('Fs','A','C','Ds')) }
testFsdim7<-function(){ parseChord('Fsdim7', c('Fs','A','C','Ds')) }
testGdim7<-function(){ parseChord('Gdim7', c('G','As','Cs','E')) }
testGsdim7<-function(){ parseChord('Gsdim7', c('Gs','B','D','F')) }
testGsdim7<-function(){ parseChord('Gsdim7', c('Gs','B','D','F')) }
testAdim7<-function(){ parseChord('Adim7', c('A','C','Ds','Fs')) }
testAsdim7<-function(){ parseChord('Asdim7', c('As','Cs','E','G')) }
testAsdim7<-function(){ parseChord('Asdim7', c('As','Cs','E','G')) }
testBdim7<-function(){ parseChord('Bdim7', c('B','D','F','Gs')) }
testCm7b5<-function(){ parseChord('Cm7(b5)', c('C','Ds','Fs','As')) }
testCsm7b5<-function(){ parseChord('Csm7(b5)', c('Cs','E','G','B')) }
testCsm7b5<-function(){ parseChord('Csm7(b5)', c('Cs','E','G','B')) }
testDm7b5<-function(){ parseChord('Dm7(b5)', c('D','F','Gs','C')) }
testDsm7b5<-function(){ parseChord('Dsm7(b5)', c('Ds','Fs','A','Cs')) }
testDsm7b5<-function(){ parseChord('Dsm7(b5)', c('Ds','Fs','A','Cs')) }
testEm7b5<-function(){ parseChord('Em7(b5)', c('E','G','As','D')) }
testFm7b5<-function(){ parseChord('Fm7(b5)', c('F','Gs','B','Ds')) }
testFsm7b5<-function(){ parseChord('Fsm7(b5)', c('Fs','A','C','E')) }
testFsm7b5<-function(){ parseChord('Fsm7(b5)', c('Fs','A','C','E')) }
testGm7b5<-function(){ parseChord('Gm7(b5)', c('G','As','Cs','F')) }
testGsm7b5<-function(){ parseChord('Gsm7(b5)', c('Gs','B','D','Fs')) }
testGsm7b5<-function(){ parseChord('Gsm7(b5)', c('Gs','B','D','Fs')) }
testAm7b5<-function(){ parseChord('Am7(b5)', c('A','C','Ds','G')) }
testAsm7b5<-function(){ parseChord('Asm7(b5)', c('As','Cs','E','Gs')) }
testAsm7b5<-function(){ parseChord('Asm7(b5)', c('As','Cs','E','Gs')) }
testBm7b5<-function(){ parseChord('Bm7(b5)', c('B','D','F','A')) }
testComaj7<-function(){ parseChord('Comaj7', c('C','Ds','Fs','B')) }
testCsomaj7<-function(){ parseChord('Csomaj7', c('Cs','E','G','C')) }
testCsomaj7<-function(){ parseChord('Csomaj7', c('Cs','E','G','C')) }
testDomaj7<-function(){ parseChord('Domaj7', c('D','F','Gs','Cs')) }
testDsomaj7<-function(){ parseChord('Dsomaj7', c('Ds','Fs','A','D')) }
testDsomaj7<-function(){ parseChord('Dsomaj7', c('Ds','Fs','A','D')) }
testEomaj7<-function(){ parseChord('Eomaj7', c('E','G','As','Ds')) }
testFomaj7<-function(){ parseChord('Fomaj7', c('F','Gs','B','E')) }
testFsomaj7<-function(){ parseChord('Fsomaj7', c('Fs','A','C','F')) }
testFsomaj7<-function(){ parseChord('Fsomaj7', c('Fs','A','C','F')) }
testGomaj7<-function(){ parseChord('Gomaj7', c('G','As','Cs','Fs')) }
testGsomaj7<-function(){ parseChord('Gsomaj7', c('Gs','B','D','G')) }
testGsomaj7<-function(){ parseChord('Gsomaj7', c('Gs','Cb','D','G')) }
testAomaj7<-function(){ parseChord('Aomaj7', c('A','C','Ds','Gs')) }
testAsomaj7<-function(){ parseChord('Asomaj7', c('As','Cs','E','A')) }
testAsomaj7<-function(){ parseChord('Asomaj7', c('As','Cs','E','A')) }
testBomaj7<-function(){ parseChord('Bomaj7', c('B','D','F','As')) }
testCmM7<-function(){ parseChord('CmM7', c('C','Ds','G','B')) }
testCsmM7<-function(){ parseChord('CsmM7', c('Cs','E','Gs','C')) }
testCsmM7<-function(){ parseChord('CsmM7', c('Cs','E','Gs','C')) }
testDmM7<-function(){ parseChord('DmM7', c('D','F','A','Cs')) }
testDsmM7<-function(){ parseChord('DsmM7', c('Ds','Fs','As','D')) }
testDsmM7<-function(){ parseChord('DsmM7', c('Ds','Fs','As','D')) }
testEmM7<-function(){ parseChord('EmM7', c('E','G','B','Ds')) }
testFmM7<-function(){ parseChord('FmM7', c('F','Gs','C','E')) }
testFsmM7<-function(){ parseChord('FsmM7', c('Fs','A','Cs','F')) }
testFsmM7<-function(){ parseChord('FsmM7', c('Fs','A','Cs','F')) }
testGmM7<-function(){ parseChord('GmM7', c('G','As','D','Fs')) }
testGsmM7<-function(){ parseChord('GsmM7', c('Gs','B','Ds','G')) }
testGsmM7<-function(){ parseChord('GsmM7', c('Gs','B','Ds','G')) }
testAmM7<-function(){ parseChord('AmM7', c('A','C','E','Gs')) }
testAsmM7<-function(){ parseChord('AsmM7', c('As','Cs','F','A')) }
testAsmM7<-function(){ parseChord('AsmM7', c('As','Cs','F','A')) }
testBmM7<-function(){ parseChord('BmM7', c('B','D','Fs','As')) }
testCaug<-function(){ parseChord('Caug', c('C','E','Gs')) }
testCsaug<-function(){ parseChord('Csaug', c('Cs','F','A')) }
testCsaug<-function(){ parseChord('Csaug', c('Cs','F','A')) }
testDaug<-function(){ parseChord('Daug', c('D','Fs','As')) }
testDsaug<-function(){ parseChord('Dsaug', c('Ds','G','B')) }
testDsaug<-function(){ parseChord('Dsaug', c('Ds','G','B')) }
testEaug<-function(){ parseChord('Eaug', c('E','Gs','C')) }
testFaug<-function(){ parseChord('Faug', c('F','A','Cs')) }
testFsaug<-function(){ parseChord('Fsaug', c('Fs','As','D')) }
testFsaug<-function(){ parseChord('Fsaug', c('Fs','As','D')) }
testGaug<-function(){ parseChord('Gaug', c('G','B','Ds')) }
testGsaug<-function(){ parseChord('Gsaug', c('Gs','C','E')) }
testGsaug<-function(){ parseChord('Gsaug', c('Gs','C','E')) }
testAaug<-function(){ parseChord('Aaug', c('A','Cs','F')) }
testAsaug<-function(){ parseChord('Asaug', c('As','D','Fs')) }
testAsaug<-function(){ parseChord('Asaug', c('As','D','Fs')) }
testBaug<-function(){ parseChord('Baug', c('B','Ds','G')) }
testCmaj7s5<-function(){ parseChord('Cmaj7(s5)', c('C','E','Gs','B')) }
testCsmaj7s5<-function(){ parseChord('Csmaj7(s5)', c('Cs','F','A','C')) }
testCsmaj7s5<-function(){ parseChord('Csmaj7(s5)', c('Cs','F','A','C')) }
testDmaj7s5<-function(){ parseChord('Dmaj7(s5)', c('D','Fs','As','Cs')) }
testDsmaj7s5<-function(){ parseChord('Dsmaj7(s5)', c('Ds','G','B','D')) }
testDsmaj7s5<-function(){ parseChord('Dsmaj7(s5)', c('Ds','G','B','D')) }
testEmaj7s5<-function(){ parseChord('Emaj7(s5)', c('E','Gs','C','Ds')) }
testFmaj7s5<-function(){ parseChord('Fmaj7(s5)', c('F','A','Cs','E')) }
testFsmaj7s5<-function(){ parseChord('Fsmaj7(s5)', c('Fs','As','D','F')) }
testFsmaj7s5<-function(){ parseChord('Fsmaj7(s5)', c('Fs','As','D','F')) }
testGmaj7s5<-function(){ parseChord('Gmaj7(s5)', c('G','B','Ds','Fs')) }
testGsmaj7s5<-function(){ parseChord('Gsmaj7(s5)', c('Gs','C','E','G')) }
testGsmaj7s5<-function(){ parseChord('Gsmaj7(s5)', c('Gs','C','E','G')) }
testAmaj7s5<-function(){ parseChord('Amaj7(s5)', c('A','Cs','F','Gs')) }
testAsmaj7s5<-function(){ parseChord('Asmaj7(s5)', c('As','D','Fs','A')) }
testAsmaj7s5<-function(){ parseChord('Asmaj7(s5)', c('As','Fs','A')) }
testBmaj7s5<-function(){ parseChord('Bmaj7(s5)', c('B','Ds','G','As')) }
testCdim<-function(){ parseChord('Cdim', c('C','Ds','Fs')) }
testCsdim<-function(){ parseChord('Csdim', c('Cs','E','G')) }
testCsdim<-function(){ parseChord('Csdim', c('Cs','E','G')) }
testDdim<-function(){ parseChord('Ddim', c('D','F','Gs')) }
testDsdim<-function(){ parseChord('Dsdim', c('Ds','Fs','A')) }
testDsdim<-function(){ parseChord('Dsdim', c('Ds','Fs','A')) }
testEdim<-function(){ parseChord('Edim', c('E','G','As')) }
testFdim<-function(){ parseChord('Fdim', c('F','Gs','B')) }
testFsdim<-function(){ parseChord('Fsdim', c('Fs','A','C')) }
testFsdim<-function(){ parseChord('Fsdim', c('Fs','A','C')) }
testGdim<-function(){ parseChord('Gdim', c('G','As','Cs')) }
testGsdim<-function(){ parseChord('Gsdim', c('Gs','B','D')) }
testGsdim<-function(){ parseChord('Gsdim', c('Gs','B','D')) }
testAdim<-function(){ parseChord('Adim', c('A','C','Ds')) }
testAsdim<-function(){ parseChord('Asdim', c('As','Cs','E')) }
testAsdim<-function(){ parseChord('Asdim', c('As','Cs','E')) }
testBdim<-function(){ parseChord('Bdim', c('B','D','F')) }
testCm7<-function(){ parseChord('Cm7', c('C','Ds','G','As')) }
testCsm7<-function(){ parseChord('Csm7', c('Cs','E','Gs','B')) }
testCsm7<-function(){ parseChord('Csm7', c('Cs','E','Gs','B')) }
testDm7<-function(){ parseChord('Dm7', c('D','F','A','C')) }
testDsm7<-function(){ parseChord('Dsm7', c('Ds','Fs','As','Cs')) }
testDsm7<-function(){ parseChord('Dsm7', c('Ds','Fs','As','Cs')) }
testEm7<-function(){ parseChord('Em7', c('E','G','B','D')) }
testFm7<-function(){ parseChord('Fm7', c('F','Gs','C','Ds')) }
testFsm7<-function(){ parseChord('Fsm7', c('Fs','A','Cs','E')) }
testFsm7<-function(){ parseChord('Fsm7', c('Fs','A','Cs','E')) }
testGm7<-function(){ parseChord('Gm7', c('G','As','D','F')) }
testGsm7<-function(){ parseChord('Gsm7', c('Gs','B','Ds','Fs')) }
testGsm7<-function(){ parseChord('Gsm7', c('Gs','B','Ds','Fs')) }
testAm7<-function(){ parseChord('Am7', c('A','C','E','G')) }
testAsm7<-function(){ parseChord('Asm7', c('As','Cs','F','Gs')) }
testAsm7<-function(){ parseChord('Asm7', c('As','Cs','F','Gs')) }
testBm7<-function(){ parseChord('Bm7', c('B','D','Fs','A')) }
testCaug7<-function(){ parseChord('Caug7', c('C','E','Gs','As')) }
testCsaug7<-function(){ parseChord('Csaug7', c('Cs','F','A','B')) }
testCsaug7<-function(){ parseChord('Csaug7', c('Cs','F','A','B')) }
testDaug7<-function(){ parseChord('Daug7', c('D','Fs','As','C')) }
testDsaug7<-function(){ parseChord('Dsaug7', c('Ds','G','B','Cs')) }
testDsaug7<-function(){ parseChord('Dsaug7', c('Ds','G','B','Cs')) }
testEaug7<-function(){ parseChord('Eaug7', c('E','Gs','C','D')) }
testFaug7<-function(){ parseChord('Faug7', c('F','A','Cs','Ds')) }
testFsaug7<-function(){ parseChord('Fsaug7', c('Fs','As','D','E')) }
testFsaug7<-function(){ parseChord('Fsaug7', c('Fs','As','D','E')) }
testGaug7<-function(){ parseChord('Gaug7', c('G','B','Ds','F')) }
testGsaug7<-function(){ parseChord('Gsaug7', c('Gs','C','E','Fs')) }
testGsaug7<-function(){ parseChord('Gsaug7', c('Gs','C','E','Fs')) }
testAaug7<-function(){ parseChord('Aaug7', c('A','Cs','F','G')) }
testAsaug7<-function(){ parseChord('Asaug7', c('As','D','Fs','Gs')) }
testAsaug7<-function(){ parseChord('Asaug7', c('As','D','Fs','Gs')) }
testBaug7<-function(){ parseChord('Baug7', c('B','Ds','G','A')) }
testC7g6<-function(){ parseChord('C76', c('C','E','G','A','As')) }
testCs7g6<-function(){ parseChord('Cs76', c('Cs','F','Gs','As','B')) }
testCs7g6<-function(){ parseChord('Cs76', c('Cs','F','Gs','As','Cb')) }
testD7g6<-function(){ parseChord('D76', c('D','Fs','A','B','C')) }
testDs7g6<-function(){ parseChord('Ds76', c('Ds','F','As','C','Cs')) }
testDs7g6<-function(){ parseChord('Ds76', c('Ds','G','As','C','Cs')) }
testE7g6<-function(){ parseChord('E76', c('E','Gs','B','Cs','D')) }
testF7g6<-function(){ parseChord('F76', c('F','A','C','D','Ds')) }
testFs7g6<-function(){ parseChord('Fs76', c('Fs','As','Cs','Ds','E')) }
testFs7g6<-function(){ parseChord('Fs76', c('Fs','As','Cs','Ds','E')) }
testG7g6<-function(){ parseChord('G76', c('G','B','D','E','F')) }
testGs7g6<-function(){ parseChord('Gs76', c('Gs','C','Ds','F','Fs')) }
testGs7g6<-function(){ parseChord('Gs76', c('Gs','C','Ds','F','Fs')) }
testA7g6<-function(){ parseChord('A76', c('A','Cs','E','Fs','G')) }
testAs7g6<-function(){ parseChord('As76', c('As','D','F','G','Gs')) }
testAs7g6<-function(){ parseChord('As76', c('As','D','F','G','Gs')) }
testB7g6<-function(){ parseChord('B76', c('B','Ds','Fs','Gs','A')) }








